
on: push

jobs:
  job1:
    runs-on: ubuntu-latest
    # Map a step output to a job output
    outputs:
      output1: abc.txt
    steps:
      - id: step1
        run: echo "Following Buses might be down:[SIBus,JMSBus]" > abc.txt

  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - run: echo ${{needs.job1.outputs.output1}}
 
  Groovy-Script:
    runs-on: windows-latest
    needs: job1
    steps:
      - name: setup Python
        uses: actions/setup-python@v3
        
      - name: run py script
        run: python timstamp.py
          
        
